name: contract test

on: [pull_request]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - run: npm install
      - uses: actions/checkout@v3
      - name: unit_test
        run: npx hardhat test
