name: contract test

on: [pull_request]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3/contract
      - name: unit_test
        run: |
          npm install
          npx hardhat test
