name: contract test

on: [pull_request]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - run: npm init -y
      - run: npm install --save-dev hardhat @openzeppelin/test-helpers
      - uses: actions/checkout@v3
      - name: unit_test
        run: npx hardhat test
